id: P073808AB
initial_creation_type: input
source_metadata:
  title: Ngor Khenpo Palden Dondrup
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    3cc3:
      title: མཁས་གྲུབ་དཔལ་ལྡན་དོན་གྲུབ་ཀྱི་གསུང་འབུམ་དཀར་ཆག
      author: ངོར་མཁན་པོ་དཔལ་ལྡན་དོན་གྲུབ།
      base_file: 3cc3.txt
      order: 1
created_at: '2022-04-06T17:07:30.583928'
last_modified_at: '2022-04-06T17:07:30.583937'
